# Generated by Django 5.1.3 on 2024-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_age', models.IntegerField()),
                ('user_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('user_weight', models.FloatField()),
                ('user_height', models.FloatField()),
                ('user_workout_choice', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('gain_muscle', 'Gain Muscle')], max_length=12)),
            ],
        ),
    ]
