# Generated by Django 5.1.3 on 2024-12-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutCompanion', '0002_workoutcompanion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcompanion',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
