# Generated by Django 5.1.3 on 2024-12-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutCompanion', '0003_workoutcompanion_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcompanion',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='workoutcompanion',
            name='user_workout_choice',
            field=models.CharField(choices=[('Lose Weight', 'lose_weight'), ('Gain Weight', 'gain_weight'), ('Gain Muscle', 'gain_muscle')], max_length=12),
        ),
    ]
