# Generated by Django 5.1.3 on 2024-12-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutCompanion', '0004_alter_workoutcompanion_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcompanion',
            name='user_workout_choice',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Gain Weight', 'Gain Weight'), ('Gain Muscle', 'Gain Muscle')], max_length=12),
        ),
    ]
